### ISSUE TITLE
Chat network using libp2p-js

### ISSUE THREAD

**Issue by varunagarwal315** [ipfs/notes#197]
I am aware of [orbit](https://github.com/haadcode/orbit) which is a distributed chat app using IPFS with data storage, CRDTS and lot more features.

However, as libp2p was modularized with the idea that it can be used independently from IPFS, I wanted to develop a distributed chat network using only libp2p. Wanted to know if anyone has thought on these lines before as I have already started an initial repo working on the same.

My thoughts were
1) Each peer will run its own libp2p-js node
2) When two nodes want to communicate one will [set up a protocol ](https://github.com/ipfs/js-libp2p-ipfs-nodejs/blob/master/examples/chat/listener.js#L29) while the other will [dial to it](https://github.com/ipfs/js-libp2p-ipfs-nodejs/blob/master/examples/chat/dialer.js#L52) opening up a `conn` in which data can be transfered via `pull-streams`
3) A set of master nodes (akin to the default bootstrap nodes in IPFS) will facilitate node discovery on the system

I am hoping for some inputs from the community to help me out freeze the architecture and proceed

**Comment by diasdavid** [comment]
Hi @varunagarwal315! We've chatted also on StackOverflow and I believe this comment was before your contribution with the chat demo. How are things going developing this app?

**Comment by varunagarwal315** [comment]
Hi @diasdavid , good to hear from you. 

I had made a very basic barebone mvp in which we ran three nodes on Azure that connected with an android app. So chat messages from the android app went to a random server which then routed the message to the other ones and finally delivers the message to the recipient's android app. Had added an initial ECIES based handshake between the server and app only for the first time they made contact.
For various reasons, we dropped the app and continued the other ethereum based smart contract project, I am still working on. Reached a point where we need IPFS (once again) for file sharing, so came back to look through the repos and saw all the sweet features added.

Though one thing I want to confirm, the data on IPFS can never be `queried` as it can in a no-sql db like mongo, because then a combination of nosqp and ipfs is probably more realistic for most if not all enterprise projects. Am I right in assuming this?

**Comment by diasdavid** [comment]
> Though one thing I want to confirm, the data on IPFS can never be queried as it can in a no-sql db like mongo, because then a combination of nosql and ipfs is probably more realistic for most if not all enterprise projects. Am I right in assuming this?

You can run those queries in mongo and other DBs because they have indexes (or they go through every document on the fly as the query is issued). If you get indexing on top of IPFS, then you can do it as well. If the question is "Is there a massive index of every single data blob hosted on IPFS for me to consume with really fast query resolution" then the answer is no, for now, just needs someone to do it :)

Check this blog post https://blog.ipfs.io/30-js-ipfs-crdts.md it is a very interesting update on CRDT space and js-ipfs.

Also, check all the new libp2p examples https://github.com/libp2p/js-libp2p/tree/master/examples they will give you a lot of more insight :)

If you don't mind, could we move this thread to `discuss.ipfs.io`, our forum like platform for this kind of threads? I'll go ahead and close this issue :)
