### ISSUE TITLE
ZenHub

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/notes#78]
(Sorry if this is the wrong repo to discuss..)

Probably most of you know about https://www.zenhub.io but I wanted to know if anyone tried it out, as I think it could be quite helpful for organizing things here on github.

**Comment by jbenet** [comment]
We considered it a long time ago, and we opted for waffle because:
- https://github.com/ZenHubIO/support/issues/213
- https://github.com/ZenHubIO/support/issues/44 <-- this seems to have been solved.
- https://github.com/ZenHubIO/support/issues/212 <-- not fixed yet

Waffle gave almost eveyrything, web based, allowed read only without installing anything, etc. We have this board:  https://waffle.io/ipfs/ipfs -- which is meta-- it includes all other repos. (well, not all of them as not all have been added).

aaaaand then, we don't even really use waffle. it's a lot of work to maintain and only works if everyone really does it. 

I'd be open to trying it out, but would need buy-in from everyone

**Comment by Dignifiedquire** [comment]
Thanks @jbenet for the details. I'm okay with using waffle, but it's not really improving so much for myself, as I have to go and use yet another website, which is the great thing for me about zenhub that it actually modifies the way I can interact with github. But I'm happy to use it for myself :)
